version: "3.1"

services:
  wasmVideoTranscoderService:
    image: node:latest
    entrypoint:
      - /bin/sh
      - ./dockerEntry.sh
    volumes:
      - $PWD:/opt/codec
    working_dir: /opt/codec
