version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    docker:
      - image: ianwalter/puppeteer:3.0.2-14.5
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: node --version
            - run: npm install
            - run: npm build
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
